import { test, expect } from '@playwright/test';

test.use({
  storageState: '.auth/flag-off-state.json'
});

test('test', async ({ page }) => {
  await page.goto('https://provider-auth.zocdoc.com/u/login/identifier?state=hKFo2SBkVDczZlJEdmhCalZHQTAxUloyRkVrZEFSM0tFUFZKSqFur3VuaXZlcnNhbC1sb2dpbqN0aWTZIDBPUWFzd0ZKZnJ1SElpX2pmSmVNQVFWb2FreGJDdFlEo2NpZNkgUjNKWERvUXdzbHdGVDFrZFBHUjNyTzllZXRBcldIYkQ');
  await page.getByRole('textbox', { name: 'Email address' }).click();
  await page.getByRole('textbox', { name: 'Email address' }).fill('first.lastname+onboardingnewGC3@zocdoctest.com');
  await page.getByRole('button', { name: 'Continue' }).click();
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('zocdoc@123');
  await page.getByRole('button', { name: 'Continue' }).click();
  await page.goto('https://www.zocdoc.com/provider/pt_2nEnZaBQbk-HBPdYLp7mOQ/home?refPageLoadId=25a63a8f-3dac-49b1-ba40-a5be266039b3');
  await page.locator('[data-test="modal-close-icon"]').click();
  await page.locator('[data-test="sidebar-collapse-toggle"]').click();
  await page.locator('[data-test="reposition-step-1-cta"]').click();
  await page.getByText('ProviderPatients can book').click();
  await page.locator('[data-test="stethoscope-icon"]').click();
  await page.locator('[data-test="provider-tile-label"]').click();
  await page.locator('[data-test="primary-button"]').click();
  await page.locator('[data-test="multi-first-name-0-input"]').click();
  await page.locator('[data-test="multi-first-name-0-input"]').fill('TestProvider test');
  await page.locator('[data-test="multi-last-name-0-input"]').click();
  await page.locator('[data-test="multi-last-name-0-input"]').fill('zocdoc');
  await page.locator('[data-test="primary-button"]').click();
  await page.locator('[data-test="empty-npi-modal-continue"]').click();
  await page.getByText('Doctor/physician').click();
  await page.locator('[data-test="primary-button"]').click();
  await page.getByText('Male', { exact: true }).click();
  await page.locator('[data-test="patient-type-checkbox-0-label-text"]').click();
  await page.locator('div').filter({ hasText: /^chevron down icon$/ }).nth(4).click();
  await page.locator('div').filter({ hasText: /^Anesthesiologist$/ }).nth(1).click();
  await page.locator('[data-test="basic-info-step"]').click();
  await page.locator('div').filter({ hasText: /^Anesthesiologist$/ }).nth(1).click();
  await page.locator('.css-53dejt-indicatorContainer > svg > path').click();
  await page.goto('https://www.zocdoc.com/provider/setup/add?practiceId=pt_2nEnZaBQbk-HBPdYLp7mOQ&task=ProvidersCreation&source=homepage_task&refPageLoadId=53ee370e-d18b-4874-bee3-267b147e371f');
  await page.getByText('ProviderPatients can book').click();
  await page.locator('[data-test="primary-button"]').click();
  await page.locator('[data-test="multi-first-name-0-input"]').click();
  await page.locator('[data-test="multi-first-name-0-input"]').fill('TestProvider test');
  await page.locator('[data-test="multi-last-name-0-input"]').click();
  await page.locator('[data-test="multi-last-name-0-input"]').fill('zocdoc');
  await page.locator('[data-test="primary-button"]').click();
  await page.locator('[data-test="empty-npi-modal-continue"]').click();
  await page.locator('[data-test="doctor-physician-tile-label"]').click();
  await page.locator('[data-test="primary-button"]').click();
  await page.getByText('Male', { exact: true }).click();
  await page.locator('[data-test="patient-type-checkbox-0-label-text"]').click();
  await page.locator('[data-test="specialty-dropdown"] svg').filter({ hasText: 'chevron down icon' }).click();
  await page.goto('https://www.zocdoc.com/provider/setup/add?practiceId=pt_2nEnZaBQbk-HBPdYLp7mOQ&task=ProvidersCreation&source=homepage_task&refPageLoadId=53ee370e-d18b-4874-bee3-267b147e371f');
  await page.locator('[data-test="provider-tile-label"]').click();
  await page.locator('[data-test="primary-button"]').click();
  await page.locator('[data-test="multi-first-name-0-input"]').click();
  await page.locator('[data-test="multi-first-name-0-input"]').fill('TestProvider test');
  await page.locator('[data-test="multi-last-name-0-input"]').click();
  await page.locator('[data-test="multi-last-name-0-input"]').fill('zocdoc');
  await page.locator('[data-test="primary-button"]').click();
  await page.locator('[data-test="empty-npi-modal-continue"]').click();
  await page.locator('[data-test="doctor-physician-tile-description"]').click();
  await page.locator('[data-test="primary-button"]').click();
  await page.getByText('Male', { exact: true }).click();
  await page.locator('[data-test="patient-type-checkbox-0-label-text"]').click();
  await page.locator('.css-saycjp').first().click();
  await page.goto('https://www.zocdoc.com/provider/setup/add?practiceId=pt_2nEnZaBQbk-HBPdYLp7mOQ&task=ProvidersCreation&source=homepage_task&refPageLoadId=53ee370e-d18b-4874-bee3-267b147e371f');
  await page.locator('[data-test="provider-tile-label"]').click();
  await page.locator('[data-test="primary-button"]').click();
  await page.locator('[data-test="multi-first-name-0-input"]').click();
  await page.locator('[data-test="multi-first-name-0-input"]').fill('mer');
  await page.locator('[data-test="multi-first-name-0-input"]').click();
  await page.locator('[data-test="multi-first-name-0-input"]').fill('TestProvider test ');
  await page.locator('[data-test="multi-last-name-0-input"]').click();
  await page.locator('[data-test="multi-last-name-0-input"]').fill('zocdoc');
  await page.locator('[data-test="primary-button"]').click();
  await page.locator('[data-test="empty-npi-modal-continue"]').click();
  await page.locator('[data-test="provider-type-step"]').click();
  await page.getByText('Doctor/physician').click();
  await page.getByText('Doctor/physician').dblclick();
  await page.locator('[data-test="primary-button"]').click();
  await page.getByText('Male', { exact: true }).click();
  await page.locator('[data-test="patient-type-checkbox-0-label-text"]').click();
  await page.locator('[data-test="specialty-dropdown"] svg').filter({ hasText: 'chevron down icon' }).click();
  await page.locator('div').filter({ hasText: /^Critical Care Specialist$/ }).nth(1).click();
  await page.getByText('What patients do you accept?').click();
  await page.locator('.css-saycjp').click();
  await page.getByText('Gender').click();
  await page.locator('[data-test="contact-first-name-wrapper"]').click();
  await page.locator('.sc-jvIDnw').first().click();
  await page.getByText('Back to HomeStep 5 of 9Basic informationFirst nameLast nameGenderFemaleMaleNon-').click();
});