import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://www.zocdoc.com/');
  await page.locator('[data-test="header-cta"]').click();
  await page.getByRole('textbox', { name: 'Enter your work email' }).click();
  await page.getByRole('textbox', { name: 'Enter your work email' }).fill('first.lastname+onboardingnewGC3@zocdoctest.com');
  await page.getByRole('button', { name: 'Get started for free' }).click();
  await page.locator('[data-test="reposition-first-name-input-input"]').fill('TestProvider test ');
  await page.locator('[data-test="reposition-last-name-input-input"]').click();
  await page.locator('[data-test="reposition-last-name-input-input"]').fill('testaccount');
  await page.locator('[data-test="reposition-first-name-input-input"]').click();
  await page.locator('[data-test="reposition-first-name-input-input"]').fill('TestProvider test  onboarding');
  await page.locator('[data-test="reposition-phone-number-input-input"]').click();
  await page.locator('[data-test="reposition-phone-number-input-input"]').fill('(203) 487-2415 ');
  await page.locator('[data-test="reposition-password-input-input"]').click();
  await page.locator('[data-test="reposition-password-input-input"]').fill('zocdo');
  await page.locator('[data-test="reposition-password-toggle"]').click();
  await page.locator('[data-test="reposition-password-input-input"]').click();
  await page.locator('[data-test="reposition-password-input-input"]').fill('zocdoc@123');
  await page.locator('[data-test="reposition-practice-name-input-input"]').click();
  await page.locator('[data-test="reposition-practice-name-input-input"]').fill('testpractice zocdoc onboardingGC3');
  await page.locator('[data-test="reposition-practice-name-input-input"]').click();
  await page.locator('[data-test="reposition-practice-name-input-input"]').click();
  await page.locator('[data-test="reposition-practice-name-input-input"]').press('ArrowLeft');
  await page.locator('[data-test="reposition-practice-name-input-input"]').press('ArrowLeft');
  await page.locator('[data-test="reposition-practice-name-input-input"]').press('ArrowLeft');
  await page.locator('[data-test="reposition-practice-name-input-input"]').press('ArrowLeft');
  await page.locator('[data-test="reposition-practice-name-input-input"]').press('ArrowRight');
  await page.locator('[data-test="reposition-practice-name-input-input"]').fill('testpractice zocdoc onboardingnewGC3');
  await page.locator('.dropdown__value-container > div:nth-child(2)').click();
  await page.locator('div').filter({ hasText: /^Dentist$/ }).nth(1).click();
  await page.locator('[data-test="reposition-form-card"]').click();
  await page.locator('div').filter({ hasText: /^Dentist$/ }).nth(1).click();
  await page.getByLabel('Open dropdown options').click();
  await page.locator('[data-test="reposition-practice-size"]').selectOption('five_providers');
  await page.goto('https://www.zocdoc.com/provider/setup/account?id=voJ1BxfAEUu4srEY8p0M-w');
  await page.locator('[data-test="reposition-confirm-email-container"]').click();
  await page.getByText('first.lastname+').click();
  await page.locator('[data-test="reposition-confirm-email-container"]').click();
});